word_list = ["about", "above", "abuse", "accept", "accident", "accuse", "across", "activist", "actor", 
             "administration", "admit", "adult", "advertise", "advise", "affect", "afraid", "after", "again", "against", 
             "agency", "aggression", "clergy", "climate", "climb", "clock", "close", "combine", 
             "agree", "agriculture", "force", "airplane", "airport", "album", "alcohol", "alive", "almost", "alone", "along", "chemistry", 
             "chief", "child", "children", "already", "although", "always", "ambassador", "amend", "ammunition", "among", "amount", "anarchy", 
             "ancestor", "command", "blind", "block", "blood", "ancient", "anger", "animal", "anniversary", "announce", "another", "answer", 
             "celebrate", "center", "century", "camera", "campaign", "cancel", "world", "atmosphere", "attach", "attack", "attempt", "attend", 
             "attention", "automobile", "autumn", "available", "average", "avoid", "bring", "bright", "awake", "award", "balance", "balloon", 
             "ballot", "barrier", "battle", "beauty", "because", "become", "before", "begin", "behavior", "brief", "teach", "behind", "believe", 
             "belong", "below", "betray", "better", "between", "biology", "black", "blame", "bleed", "sympathy", "system", "target", "taste",
             "border", "borrow", "bottle", "bottom", "boycott", "brain", "brave", "bread", "break", "breathe", "bridge", "identify", "ignore", 
             "illegal", "truck", "trust", "under", "understand", "unite", "universe", "university", "troops", "trouble", "truce",
             "imagine", "broadcast", "brother", "brown", "budget", "build", "building", "bullet", "burst", "business", "cabinet",  "honor", 
             "horrible", "horse", "crime", "cancer", "candidate", "capital", "capture", "career", "careful", "carry", "catch", "cause", "ceasefire", 
             "tense", "terrible", "territory", "terror", "ceremony", "chairman", "champion", "chance", "change", "charge", "chase", "cheat", 
             "cheer", "chemicals",  "terrorist", "telephone", "telescope", "choose", "circle", "citizen", "civilian", "civil", "rights", "claim", 
             "clash", "class", "clean", "clear",  "television", "temperature", "temporary", "cloth", "clothes", "cloud", "coalition", "coast", 
             "coffee", "collapse", "collect", "college", "colony", "color",  "technical", "technology", "comment", "committee", "common", 
             "communicate", "community", "company", "compare", "compete", "complete", "complex", "compromise", "wound", "wreck", "cooperate", 
             "correct", "corruption", "cotton", "count", "country", "court", "cover", "crash", "create", "creature", "credit", "violate", 
             "violence", "happen", "happy", "harvest", "headquarters", "health", "heavy", "helicopter", "hijack", "history", "holiday", "honest", 
             "worry", "worse", "worth", "hospital", "hostage", "hostile", "hotel", "house", "however", "human", "humor", "hunger", "hurry", 
             "husband",  "visit", "voice", "volcano", "surface", "surplus", "surprise", "surrender", "surround", "survive", "suspect", "suspend", 
             "swallow", "swear", "sweet", "unless", "until", "urgent", "thank", "theater", "theory", "there", "these", "thick", "thing", "think", 
             "third", "threaten", "through", "wreckage", "write", "wrong", "throw", "tired", "today", "together", "tomorrow", "tonight", "torture", 
             "total", "touch", "toward", "trade", "tradition", "traffic", "tragic", "train", "transport", "transportation", "travel", "treason", 
             "treasure", "treat", "treatment", "treaty", "trial", "tribe", "trick", "usual", "vacation", "vaccine", "valley", "value", "vegetable", 
             "vehicle", "version", "victim", "victory", "video", "village", "willing", "window", "winter", "withdraw", "without", "witness", 
             "woman", "wonder", "wonderful", "yellow", "yesterday", "young" ]